Server:
  Secret: ~!@e-safe2021 # App secret, used to encrypt and decrypt password
  Host: localhost # Server host
  Port: 8081 # Server port
Locksmith:
  Port: 5000 # Locksmith RPC port
Node:
  HeartbeatInterval: 2 # check heartbeat every n seconds
  CoordinatorMonitorInterval: 1 # check and update coordinator every n seconds
  VirtualNodesCount: 3 # Number of virtual nodes for each node
  ReplicationFactor: 3 # Number of replication to perform
