Server:
  Host: localhost
  Port: 8080
Locksmith:
  Port: 5000
Node:
  HeartbeatInterval: 2 # check heartbeat every n seconds
  CoordinatorMonitorInterval: 1 # check and update coordinator every n seconds
  VirtualNodesCount: 3 # Number of virtual nodes for each node
