name: Go

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:

  lint:
      name: Lint
      runs-on: ubuntu-latest
      steps:
        - name: Set up Go
          uses: actions/setup-go@v1
          with:
            go-version: 1.15

        - name: Check out code
          uses: actions/checkout@v1
          
        - name: Install dependencies
          run: |
            go version
            go get -u golang.org/x/lint/golint

        - name: Run vet & lint
          run: golint .
            
#   test:
#     strategy:
#       matrix:
#         go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x]
#         platform: [ubuntu-latest, macos-latest, windows-latest]
    
#     runs-on: ${{ matrix.platform }}

#     steps:
#     - name: Install Go
#       uses: actions/setup-go@v2
#       with:
#         go-version: ${{ matrix.go-version }}

#     - name: Checkout code
#       uses: actions/checkout@v2
    
#     - name: Test
#       run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: make build
